import * as vscode from 'vscode';
import * as path from 'path';
import { Store } from './store';
import { Flow, Annotation } from './types';

/**
 * Markdown exporter for flows.
 *
 * Generates a structured markdown document per flow that looks like:
 *
 * # Flow: Auth Bypass via SQL Injection [vuln]
 *
 * > User-controlled input reaches a raw SQL query without sanitization.
 *
 * ## Step 1 — `src/auth/login.py:42` [high]
 *
 * User input from request body is extracted without validation.
 *
 * ```python
 * username = request.form.get('username')
 * password = request.form.get('password')
 * ```
 *
 *   ↓
 *
 * ## Step 2 — `src/db/query.py:91` [critical]
 * ...
 *
 * This format works great for:
 * - PR review comments (paste into GitHub/GitLab)
 * - OSWE exam notes (static analysis documentation)
 * - Architecture walkthroughs
 */

export class Exporter {
  constructor(private store: Store, private workspaceRoot: string) {}

  /** Renders a flow's content as lines (no document-level footer). Used internally and by exportFlow. */
  private async buildFlowLines(flow: Flow): Promise<string[]> {
    const lines: string[] = [];

    lines.push(`# Flow: ${flow.name}`);
    lines.push('');

    if (flow.description) {
      lines.push(`> ${flow.description}`);
      lines.push('');
    }

    lines.push(`- **Created:** ${this.formatDate(flow.createdAt)}`);
    lines.push(`- **Updated:** ${this.formatDate(flow.updatedAt)}`);
    lines.push(`- **Steps:** ${flow.steps.length}`);
    lines.push('');
    lines.push('---');
    lines.push('');

    for (let i = 0; i < flow.steps.length; i++) {
      const step = flow.steps[i];
      const ann = this.store.getAnnotation(step.annotationId);
      if (!ann) {
        lines.push(`## Step ${i + 1} — ⚠️ *annotation not found*`);
        lines.push('');
        continue;
      }

      const line = ann.range.startLine + 1;
      const endLine = ann.range.endLine + 1;

      lines.push(`## Step ${i + 1} — \`${ann.filePath}:${line}\``);
      lines.push('');
      lines.push(ann.comment);
      lines.push('');
      lines.push(`<sub>${ann.filePath} · lines ${line}–${endLine}</sub>`);
      lines.push('');

      if (step.note) {
        lines.push(`> **Flow note:** ${step.note}`);
        lines.push('');
      }

      if (i < flow.steps.length - 1) {
        lines.push('<p align="center">⬇️</p>');
        lines.push('');
      }
    }

    return lines;
  }

  async exportFlow(flow: Flow): Promise<string> {
    const lines = await this.buildFlowLines(flow);
    lines.push('---');
    lines.push(`*Generated by [Carabiner](https://github.com/josetapadas/Carabiner) · ${new Date().toISOString()}*`);
    lines.push('');
    return lines.join('\n');
  }

  async exportAllFlows(): Promise<string> {
    const flows = this.store.getAllFlows();
    const allAnnotations = this.store.getAllAnnotations();
    const projects = this.store.getAllProjects();

    // Collect annotation IDs that are referenced by at least one flow step
    const referencedIds = new Set<string>();
    for (const flow of flows) {
      for (const step of flow.steps) {
        referencedIds.add(step.annotationId);
      }
    }

    // Loose = annotations not in any flow
    const looseAnnotations = Object.values(allAnnotations).filter(
      (a) => !referencedIds.has(a.id)
    );

    if (flows.length === 0 && looseAnnotations.length === 0) {
      return '# Carabiner Report — No annotations yet\n';
    }

    const sections: string[] = [];
    sections.push('# Carabiner Report');
    sections.push('');
    sections.push(`**Generated:** ${this.formatDate(new Date().toISOString())}`);
    sections.push('');

    const renderFlows = async (fList: typeof flows) => {
      if (fList.length === 0) { return; }
      for (let i = 0; i < fList.length; i++) {
        const anchor = fList[i].name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        sections.push(`${i + 1}. [${fList[i].name}](#${anchor}) — ${fList[i].steps.length} steps`);
      }
      sections.push('');
      sections.push('---');
      sections.push('');
      for (const flow of fList) {
        const flowLines = await this.buildFlowLines(flow);
        sections.push(...flowLines);
        sections.push('');
      }
    };

    const renderNotes = (notes: Annotation[]) => {
      if (notes.length === 0) { return; }
      sections.push(`> ${notes.length} note${notes.length !== 1 ? 's' : ''}`);
      sections.push('');
      const byFile = new Map<string, Annotation[]>();
      for (const ann of notes) {
        if (!byFile.has(ann.filePath)) { byFile.set(ann.filePath, []); }
        byFile.get(ann.filePath)!.push(ann);
      }
      for (const [filePath, anns] of byFile) {
        sections.push(`### \`${filePath}\``);
        sections.push('');
        for (const ann of anns) {
          const line = ann.range.startLine + 1;
          const endLine = ann.range.endLine + 1;
          sections.push(`#### Line ${line}`);
          sections.push('');
          sections.push(ann.comment);
          sections.push('');
          sections.push(`<sub>${filePath} · lines ${line}–${endLine}</sub>`);
          sections.push('');
        }
      }
    };

    if (projects.length > 0) {
      // ── Per-project sections ──────────────────────────────
      for (const project of projects) {
        const pFlows = flows.filter((f) => f.projectId === project.id);
        const pNotes = looseAnnotations.filter((a) => a.projectId === project.id);
        if (pFlows.length === 0 && pNotes.length === 0) { continue; }

        sections.push(`## Project: ${project.name}`);
        sections.push('');

        if (pFlows.length > 0) {
          sections.push('### Flows');
          sections.push('');
          await renderFlows(pFlows);
        }
        if (pNotes.length > 0) {
          sections.push('### Notes');
          sections.push('');
          renderNotes(pNotes);
        }
      }

      // ── Unassigned ────────────────────────────────────────
      const unassignedFlows = flows.filter((f) => !f.projectId);
      const unassignedNotes = looseAnnotations.filter((a) => !a.projectId);

      if (unassignedFlows.length > 0 || unassignedNotes.length > 0) {
        sections.push('## Unassigned');
        sections.push('');
        if (unassignedFlows.length > 0) {
          sections.push('### Flows');
          sections.push('');
          await renderFlows(unassignedFlows);
        }
        if (unassignedNotes.length > 0) {
          sections.push('### Notes');
          sections.push('');
          renderNotes(unassignedNotes);
        }
      }
    } else {
      // ── Flat layout (no projects) ─────────────────────────
      if (flows.length > 0) {
        sections.push('## Flows');
        sections.push('');
        await renderFlows(flows);
      }

      if (looseAnnotations.length > 0) {
        sections.push('## Notes');
        sections.push('');
        sections.push(`> ${looseAnnotations.length} note${looseAnnotations.length !== 1 ? 's' : ''} not assigned to any flow.`);
        sections.push('');
        sections.push('---');
        sections.push('');
        renderNotes(looseAnnotations);
      }
    }

    sections.push('---');
    sections.push(`*Generated by [Carabiner](https://github.com/josetapadas/Carabiner) · ${new Date().toISOString()}*`);
    sections.push('');

    return sections.join('\n');
  }

  /** Export a report scoped to a single project. */
  async exportProject(projectId: string): Promise<string> {
    const project = this.store.getProject(projectId);
    if (!project) { return '# Carabiner Report — Project not found\n'; }

    const allFlows = this.store.getAllFlows();
    const allAnnotations = this.store.getAllAnnotations();

    const referencedIds = new Set<string>();
    for (const flow of allFlows) {
      for (const step of flow.steps) {
        referencedIds.add(step.annotationId);
      }
    }

    const pFlows = allFlows.filter((f) => f.projectId === projectId);
    const pNotes = Object.values(allAnnotations).filter(
      (a) => a.projectId === projectId && !referencedIds.has(a.id)
    );

    if (pFlows.length === 0 && pNotes.length === 0) {
      return `# Carabiner Report — ${project.name}\n\nNo flows or notes in this project yet.\n`;
    }

    const sections: string[] = [];
    sections.push(`# Carabiner Report — ${project.name}`);
    sections.push('');
    sections.push(`**Generated:** ${this.formatDate(new Date().toISOString())}`);
    sections.push('');

    if (pFlows.length > 0) {
      sections.push('## Flows');
      sections.push('');
      for (let i = 0; i < pFlows.length; i++) {
        const anchor = pFlows[i].name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        sections.push(`${i + 1}. [${pFlows[i].name}](#${anchor}) — ${pFlows[i].steps.length} steps`);
      }
      sections.push('');
      sections.push('---');
      sections.push('');
      for (const flow of pFlows) {
        const flowLines = await this.buildFlowLines(flow);
        sections.push(...flowLines);
        sections.push('');
      }
    }

    if (pNotes.length > 0) {
      sections.push('## Notes');
      sections.push('');
      sections.push(`> ${pNotes.length} note${pNotes.length !== 1 ? 's' : ''}`);
      sections.push('');
      const byFile = new Map<string, Annotation[]>();
      for (const ann of pNotes) {
        if (!byFile.has(ann.filePath)) { byFile.set(ann.filePath, []); }
        byFile.get(ann.filePath)!.push(ann);
      }
      for (const [filePath, anns] of byFile) {
        sections.push(`### \`${filePath}\``);
        sections.push('');
        for (const ann of anns) {
          const line = ann.range.startLine + 1;
          const endLine = ann.range.endLine + 1;
          sections.push(`#### Line ${line}`);
          sections.push('');
          sections.push(ann.comment);
          sections.push('');
          sections.push(`<sub>${filePath} · lines ${line}–${endLine}</sub>`);
          sections.push('');
        }
      }
    }

    sections.push('---');
    sections.push(`*Generated by [Carabiner](https://github.com/josetapadas/Carabiner) · ${new Date().toISOString()}*`);
    sections.push('');

    return sections.join('\n');
  }

  /** Read the annotated code range from the actual file on disk */
  private async readSnippet(ann: Annotation): Promise<string | null> {
    try {
      const absPath = path.join(this.workspaceRoot, ann.filePath);
      const uri = vscode.Uri.file(absPath);
      const doc = await vscode.workspace.openTextDocument(uri);

      const startLine = Math.max(0, ann.range.startLine);
      const endLine = Math.min(doc.lineCount - 1, ann.range.endLine);

      const lines: string[] = [];
      for (let i = startLine; i <= endLine; i++) {
        lines.push(doc.lineAt(i).text);
      }
      return lines.join('\n');
    } catch {
      return null;
    }
  }

  private detectLanguage(filePath: string): string {
    const ext = path.extname(filePath).toLowerCase();
    const map: Record<string, string> = {
      '.py': 'python',
      '.js': 'javascript',
      '.ts': 'typescript',
      '.jsx': 'jsx',
      '.tsx': 'tsx',
      '.go': 'go',
      '.rs': 'rust',
      '.rb': 'ruby',
      '.java': 'java',
      '.c': 'c',
      '.cpp': 'cpp',
      '.h': 'c',
      '.hpp': 'cpp',
      '.cs': 'csharp',
      '.php': 'php',
      '.sql': 'sql',
      '.sh': 'bash',
      '.bash': 'bash',
      '.zsh': 'bash',
      '.yaml': 'yaml',
      '.yml': 'yaml',
      '.json': 'json',
      '.xml': 'xml',
      '.html': 'html',
      '.css': 'css',
      '.lua': 'lua',
      '.r': 'r',
      '.swift': 'swift',
      '.kt': 'kotlin',
      '.scala': 'scala',
      '.ex': 'elixir',
      '.exs': 'elixir',
      '.erl': 'erlang',
      '.hs': 'haskell',
      '.pl': 'perl',
      '.ps1': 'powershell',
    };
    return map[ext] || '';
  }

  private formatDate(iso: string): string {
    const d = new Date(iso);
    return d.toLocaleDateString('en-GB', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }
}
